# TCL File Generated by Component Editor 23.1
# Wed Oct 15 16:24:17 BRT 2025
# DO NOT MODIFY


# 
# img_ram "img_ram" v1.0
#  2025.10.15.16:24:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module img_ram
# 
set_module_property DESCRIPTION ""
set_module_property NAME img_ram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME img_ram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ImgRam
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ImgRam.v VERILOG PATH ip/ImgRam.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point imgram_ports
# 
add_interface imgram_ports conduit end
set_interface_property imgram_ports associatedClock clock
set_interface_property imgram_ports associatedReset reset
set_interface_property imgram_ports ENABLED true
set_interface_property imgram_ports EXPORT_OF ""
set_interface_property imgram_ports PORT_NAME_MAP ""
set_interface_property imgram_ports CMSIS_SVD_VARIABLES ""
set_interface_property imgram_ports SVD_ADDRESS_GROUP ""

add_interface_port imgram_ports q data_out Output 8
add_interface_port imgram_ports rdaddress read_add Input 15
add_interface_port imgram_ports wraddress write_add Input 15
add_interface_port imgram_ports wren write_enable Input 1
add_interface_port imgram_ports data data_in Input 8


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

